# 1. 예외처리(exception handling)
## 1.1 프로그램 오류
- 컴파일 에러와 런타임 에러
```java
   컴파일 에러 - 컴파일 시에 발생하는 에러
   런타임 에러 - 실행 시에 발생하는 에러
   논리적 에러 - 실행은 되지만, 의도와 다르게 동작하는 것 
```

<br>

- Java의 런타임 에러 - 에러(error)와 예(exception)
```java
   에러(error)      - 프로그램 코드에 의해서 수습될 수 없는 심각한 오류
   예외(exception)  - 프로그램 코드에 의해서 수습될 수 있는 다소 미약한 오류
```

<br>

## 1-2 예외처리의 정의와 목적
- 에러는 어쩔 수 없지만, 예외는 처리해야 한다.
- 예외처리의 정의와 목적
```java
예외처리의 
정의 - 프로그램 실행 시 발생할 수 있는 예외의 발생에 대비한 코드를 작성하는 것
목적 - 프로그램의 비정상 종료를 막고, 정상적인 실행상태를 유지하는 것
```

<br>

## 1-3 예외 클래스의 계층구조
- 예외 클래스는 크게 두 그룹으로 나뉜다.
```java
RuntimeException클래스들 - 프로그래머의 실수로 발생하는 예외 <- 예외처리 선택
Exception클래스들 - 사용자의 실수와 같은 외적인 요인에 의해 발생하는 예외 <- 예외처리 필수
```

<img width="684" alt="스크린샷 2023-03-29 오후 4 27 44" src="https://user-images.githubusercontent.com/121492344/228459414-c574a5e4-12f1-475f-98c3-a19805aa292f.png">

<br>

## 1-4 예외처리구문 - try-catch
- 예외를 처리하려면 try-catch문을 사용해야 한다.
```java
try {
    //  예외가 발생할 가능성이 있는 문장들을 넣는다.
} catch (Exception e1) {
    // Exception1이 발생했을 경우, 이를 처리하기 위한 문장을 적는다.
} catch (Exception e2){
    // Exception2가 발생했을 경우, 이를 처리하기 위한 문장을 적는다.
} catch (Exception eN){
    // ExceptionN이 발생했을 경우, 이를 처리하기 위한 문장을 적는다.
}
```
하나의 try블럭 다음에 여러 종류의 예외를 처리할 수 있도록 하나 이상의 catch블럭이 올 수 있으며, 이 중 발생한 예외의 종류와 일치하는 단 한 개의 catch블럭만 수행된다.

```java
public class ExceptionEx1 {
    public static void main(String[] args) {
        try {
            try {   } catch (Exception e) {  
                //...
            }
        } catch (Exception e) {
            try {   } catch (Exception e) { // 에러. 변수 e가 중복 선언되었다.  
                //...
            }   
        } // try-catch의 끝 
    }
}
```
하나의 메서드 내에 여러 개의 try-catch문이 사용될 수 있으며, try블럭 또는 cath블럭에 또 다른 try-catch문이 포함될 수 있다. catch블럭 내의 코드에서도 예외가 발생할 수 있기 때문이다. 
catch블럭의 괄호 내에 선언된 변수는 catch블럭 내에서만 유용하기 때문에, 위 모든 블럭에 참조변수 'e'하나만을 사용해도 된다. 그러나 catch블럭 내에 또 하나의 try-catch문이 포함된 경우, 같은 이름의 참조변수를 사용해서는 안 된다.

<br>

## 1-5 try-catch문에서의 흐름
```java
 - try블럭 내에서 예외가 발생한 경우.
1. 발생한 예외와 일치하는 catch블럭이 있는지 확인한다.
2. 일치하는 catch블럭을 찾게 되면, 그 catch블럭 내의 문장들을 수행하고 전체 try-catch문을 빠져나가서 그 다음 문장을 계속해서 수행한다.
   만일 일치하는 catch블럭을 찾지 못하면, 예외는 처리되지 못한다.

 - try블럭 내에서 예외가 발생하지 않은 경우
1. catch블럭을 거치지 않고 전체 try-catch문을 빠져나가서 수행을 계속한다.
```

```java
public class ExceptionEx4 {
    public static void main(String[] args) {
        System.out.println(1);
        System.out.println(2);
        try {
            System.out.println(3);
            System.out.println(4);
        } catch (Exception e) {
            System.out.println(5);  // 실행되지 않는다.
        } // try-catch의 끝
        System.out.println(6);
    }
}
```
```java
실행 결과
1
2
3
4
6
```

<br>

```java
public class ExceptionEx5 {
    public static void main(String[] args) {
        System.out.println(1);
        System.out.println(2);
        try {
            System.out.println(3);
            System.out.println(0/0); // 예외 발생
            System.out.println(4);   // 실행되지 않는다.
        } catch (ArithmeticException ae) {
            System.out.println(5);
        }
        System.out.println(6);
    }
}
```

```
실행 결과
1
2
3
5
6
```

<br>

## 1-6 예외의 발생과 catch블럭
- try블럭에서 예외가 발생하면, 발생한 예외를 처리할 catch블럭을 찾는다.
- 첫번째 catch블럭부터 순서대로 찾아 내려가며, 일치하는 catch블럭이 없으면 예외는 처리되지 않는다.
- 예외의 최고 조상인 Exception을 처리하는 catch블럭은 모든 종류의 예외를 처리할 수 있다. (반드시 마지막 catch블럭이어야 함)

```java
public class ExceptionEx4 {
    public static void main(String[] args) {
        System.out.println(1);
        System.out.println(2);

        try {
            System.out.println(3);
            System.out.println(0/0);  // 0으로 나눠서 ArithmeticException을 발생시킴.
            System.out.println(4);
        } catch (ArithmeticException ae) { // ArithmeticException 예외처리.
            if (ae instanceof ArithmeticException)
                System.out.println("true");
                System.out.println("ArithmeticException");
        } catch (Exception e) {  // ArithmeticException을 제외한 모든 예외가 처리된다.
            System.out.println("Exception");
        }   // try-catch의 끝
        System.out.println(6);
    }
}
```
```java
실행결과
1 
2 
3
true 
ArithmeticException 
6
```

<br>

- 발생한 예외 객체를 getMessage()와 printStackTrace()를 통해서 이 정보들을 얻을 수 있다.
- catch블럭의 괄호()에 선언된 참조변수를 통해 이 인스턴스에 접근할 수 있다.

```java
  printStackTrace() - 예외발생 당시의 호출스택에 있었던 메서드의 정보와 예외 메시지를 화면에 출력한다

  getMessage()      - 발생한 예외클래스의 인스턴스에 저장된 메시지를 얻을 수 있다.
```
```java
public class ExceptionEx8 {
    public static void main(String[] args) {
        System.out.println(1);
        System.out.println(2);
        try {
            System.out.println(3);
            System.out.println(0/0);  // ArithmeticException 발생
            System.out.println(4);    // 실행되지 않는다.
        } catch (ArithmeticException ae)  {
            ae.printStackTrace();   // 참조변수 ae를 통해 생성된 ArithmeticException 인스턴스에 접근할 수 있다.
            System.out.println("예외메시지 : " + ae.getMessage());
        }   // try-catch의 끝
        System.out.println(6);
    }
}
```
```java
실행결과
1
2
3
java.lang.ArithmeticException: / by zero
        at exercise.ExceptionEx8.main(ExceptionEx8.java:9)
예외메시지 : / by zero
6
```
위 예제 결과는 예외가 발생해서 비정상적으로 종료되었을 때의 결과와 비슷하지만 예외는 try-catch문에 의해 처리되었으며 프로그램은 정상적으로 종료되었다. 
이처럼 try-catch문으로 예외처리를 하여 예외가 발생해도 비정상적으로 종료하지 않도록 해주는 동시에, printStackTrace() 또는 getMessage()와 같은 메서드를 통해서 예외의 발생원인을 알 수 있다.


<br>

**멀티 catch블럭**
JDK1.7부터 여러 catch블럭을 '|' 기호를 이용해서 하나의 catch블럭으로 합칠 수 있게 되었다. '|'기호로 연결할 수 있는 예외 클래스의 개수에는 제한이 없다.
```java
try {
    ...
} catch (ExceptionA e) {
    e.printStackTrace();
} catch (ExceptionB e2) {
    e2.printStackTrace();
}
```
⬇️
```java
try {
        ...
} catch (ExceptionA |ExceptionB e) {
    e.printStackTrace();
}
```
만일 멀티 catch블럭의 '|'기호로 연결된 예외 클래스가 조상과 자손의 관계에 있다면 컴파일 에러가 발생한다. 두 예외 클래스가 조상과 자손의 관계에 있다면, 
그냥 조상 클래스만 써주는 것과 똑같기 때문이다.

## 1-7 예외 발생시키기
키워드 throw를 사용해서 프로그래머가 고의로 예외를 발생시킬 수 있다.
```java
1. 먼저, 연산자 new를 이용해서 발생시키려는 예외 클래스의 객체를 만든 다음
    Exception e = new Exception("고의로 발생시켰음");

2. 키워드 throw를 이용해서 예외를 발생시킨다.
    throw e;
```

```java
public class ExceptionEx9 {
    public static void main(String[] args) {
        try {
            Exception e = new Exception("고의로 발생시켰음.");     // 발생시키려는 예외 클래스의 객체를 생성.
            throw e;   // 예외를 발생시킴.
          //throw new Exception("고의로 발생시켰음");     위 두 줄을 한 줄로 줄여 쓸 수 있다.

        } catch (Exception e) {
            System.out.println("에러 메시지 : " + e.getMessage());
            e.printStackTrace();
        }
        System.out.println("프로그램이 정상 종료되었음.");
    }
}
```
```java
실행결과
에러 메시지 : 고의로 발생시켰음.
프로그램이 정상 종료되었음.
java.lang.Exception: 고의로 발생시켰음.
    at exercise.ExceptionEx9.main(ExceptionEx9.java:6)
```
Exception인스턴스를 생성할 때, 생성자에 String을 넣어주면, 이 String이 Exception인스턴스에 메시지로 저장된다. 
이 메시지는 getMessage()를 이용해서 얻을 수 있다. 

<br>

- 컴파일러가 예외처리를 확인하지 않는 Exception클래스들은 'checked예외' 라고 부른다.
- 컴파일러가 예외처리를 확인하는 RuntimeException클래스들은 'unchecked예외' 라고 부른다.

<br>


## 1-8 메서드에 예외 선언하기
- 메서드에 예외를 선언하려면, 메서드의 선언부에 키워드 throws를 사용해서 메서드 내에서 발생할 수 있는 예외를 적어주면 된다.
- 예외가 여러 개일 경우에는 쉽표','로 구분한다. 
- 사실 예외를 메서드의 throws에 명시하는 것은 예외를 처리하는 것이 아니라, 자신을 호출한 메서드에게 예외를 전달하여 예외처리를 떠맡기는 것이다.
- 호출한 메서드에서 예외처리를 해야만 할 때 사용한다. 

```java
void method() throws Exception1, Exception2, ... ExceptionN {
    // 메서드의 내용
}
```

Java API문서를 통해 사용하고자 하는 메서드의 선언부와 "Throws:"를 보고, 이 메서드에서는 어떤 예외가 발생할 수 있으며 반드시 처리해주어야 하는 예외는 
어떤 것들이 있는지 확인하는 것이 좋다. 

```java
public class ExceptionEx12 {
    public static void main(String[] args) throws Exception{
        method1();      // 같은 클래스내의 static멤버이므로 객체 생성없이 직접 호출가능.
    }

    static void method1() throws Exception {
        method2();
    }

    static void method2() throws Exception {
        throw new Exception();
    }
}
```
```java
실행결과
Exception in thread "main" java.lang.Exception
	at exercise.ExceptionEx12.method2(ExceptionEx12.java:13)
	at exercise.ExceptionEx12.method1(ExceptionEx12.java:9)
	at exercise.ExceptionEx12.main(ExceptionEx12.java:5)
```

<img width="734" alt="스크린샷 2023-03-30 오전 11 18 19" src="https://user-images.githubusercontent.com/121492344/228711077-57e1b6b6-5f78-4038-9970-cd604d775eca.png">

```java
1. 예외가 발생했을 때, 모두 3개의 메서드(main, method1, method2)가 호출스택에 있었으며, 
2. 예외가 발생한 곳은 제일 윗줄에 있는 method2()라는 것과
3. main메서드가 method1()을, 그리고 method1()은 method2()를 호출했다는 것을 알 수 있다. 
```

<br>

## 1-9 finally블럭














